apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auto-broker-api
  namespace: auto-broker
  labels:
    app.kubernetes.io/name: auto-broker
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auto-broker
      app.kubernetes.io/component: api
